import type { Config } from "tailwindcss";

const config: Config = {
    darkMode: ["class"],
    content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}"
  ],
  safelist: [
    // Classes críticas do modal que podem ser purgadas
    'w-[95vw]',
    'max-h-[80vh]',
    'max-h-[85vh]',
    'max-h-[50vh]',
    'pb-32',
    '-top-2',
    '-right-2',
    'bg-red-500',
    'hover:bg-red-600',
    'bg-black/80',
    'text-[10px]',
    'text-[11px]',
    'w-6',
    'h-6',
    'w-10',
    'h-10',
    'w-12',
    'h-12',
    'w-24',
    'w-3',
    'h-3',
    'w-4',
    'h-4',
    'w-5',
    'h-5',
    'w-8',
    'h-8',
    // Todas as classes do componente catalog/page.tsx
    'min-h-screen',
    'bg-gray-50',
    'flex',
    'items-center',
    'justify-center',
    'overflow-hidden',
    'text-center',
    'animate-spin',
    'rounded-full',
    'h-12',
    'border-b-2',
    'border-indigo-600',
    'mx-auto',
    'mb-4',
    'p-4',
    'w-full',
    'max-w-md',
    'p-6',
    'w-12',
    'text-red-500',
    'text-xl',
    'font-bold',
    'mb-2',
    'text-gray-600',
    'mb-4',
    'space-y-2',
    'w-full',
    'variant-outline',
    'w-4',
    'mr-2',
    'sticky',
    'top-0',
    'bg-white',
    'border-b',
    'z-20',
    'max-w-4xl',
    'items-center',
    'justify-between',
    'p-4',
    'w-[120px]',
    'font-medium',
    'text-center',
    'variant-default',
    'variant-secondary',
    'text-gray-400',
    'left-3',
    'transform',
    '-translate-y-1/2',
    'w-4',
    'h-4',
    'pl-10',
    'text-sm',
    'text-gray-600',
    'font-bold',
    'text-indigo-600',
    'pb-20',
    'overflow-y-auto',
    'py-12',
    'text-gray-500',
    'mb-8',
    'text-xl',
    'mb-4',
    'text-gray-900',
    'relative',
    'overflow-x-auto',
    'pb-4',
    'inline-flex',
    'gap-3',
    'min-w-full',
    'transition-all',
    'flex-shrink-0',
    'w-[200px]',
    'ring-2',
    'ring-indigo-500',
    'cursor-default',
    'opacity-50',
    'cursor-pointer',
    'hover:shadow-md',
    'p-0',
    'aspect-square',
    'object-cover',
    'w-full',
    'h-full',
    'select-none',
    'absolute',
    'inset-0',
    'pointer-events-none',
    'opacity-40',
    'bg-indigo-500',
    'bg-opacity-20',
    'p-2',
    'text-sm',
    'font-medium',
    'py-4',
    'h-8',
    'text-gray-500',
    'mt-2',
    'sm:w-auto',
    'sm:max-w-lg',
    'md:max-w-2xl',
    'lg:max-w-3xl',
    'xl:max-w-4xl',
    'max-w-full',
    'p-0',
    'flex-col',
    'px-4',
    'pt-4',
    'pb-2',
    'justify-center',
    'mb-3',
    'text-yellow-500',
    'text-lg',
    'sm:text-xl',
    'text-sm',
    'sm:text-base',
    'flex-1',
    'overflow-hidden',
    'space-y-4',
    'text-gray-700',
    'grid',
    'grid-cols-3',
    'sm:grid-cols-4',
    'lg:grid-cols-6',
    'gap-3',
    'overflow-y-auto',
    'px-4',
    'pt-4',
    'rounded-lg',
    'border-2',
    'border-gray-200',
    'bg-gray-100',
    'text-center',
    'text-xs',
    'w-10',
    'sm:w-12',
    'rounded-full',
    'text-white',
    'transition-colors',
    'shadow-md',
    'text-xs',
    'mt-1',
    'text-gray-600',
    'truncate',
    'sticky',
    'bottom-0',
    'border-t',
    'p-3',
    'sm:p-4',
    'items-start',
    'sm:items-center',
    'gap-3',
    'px-1',
    'sm:px-2',
    'mb-2',
    'text-sm',
    'sm:text-base',
    'leading-snug',
    'sm:leading-none',
    'fixed',
    'bottom-4',
    'left-0',
    'right-0',
    'justify-center',
    'size-lg',
    'shadow-lg',
    'mr-2'
  ],
  theme: {
  	extend: {
  		colors: {
  			background: 'hsl(var(--background))',
  			foreground: 'hsl(var(--foreground))',
  			card: {
  				DEFAULT: 'hsl(var(--card))',
  				foreground: 'hsl(var(--card-foreground))'
  			},
  			popover: {
  				DEFAULT: 'hsl(var(--popover))',
  				foreground: 'hsl(var(--popover-foreground))'
  			},
  			primary: {
  				DEFAULT: 'hsl(var(--primary))',
  				foreground: 'hsl(var(--primary-foreground))'
  			},
  			secondary: {
  				DEFAULT: 'hsl(var(--secondary))',
  				foreground: 'hsl(var(--secondary-foreground))'
  			},
  			muted: {
  				DEFAULT: 'hsl(var(--muted))',
  				foreground: 'hsl(var(--muted-foreground))'
  			},
  			accent: {
  				DEFAULT: 'hsl(var(--accent))',
  				foreground: 'hsl(var(--accent-foreground))'
  			},
  			destructive: {
  				DEFAULT: 'hsl(var(--destructive))',
  				foreground: 'hsl(var(--destructive-foreground))'
  			},
  			border: 'hsl(var(--border))',
  			input: 'hsl(var(--input))',
  			ring: 'hsl(var(--ring))',
  			chart: {
  				'1': 'hsl(var(--chart-1))',
  				'2': 'hsl(var(--chart-2))',
  				'3': 'hsl(var(--chart-3))',
  				'4': 'hsl(var(--chart-4))',
  				'5': 'hsl(var(--chart-5))'
  			},
  			sidebar: {
  				DEFAULT: 'hsl(var(--sidebar-background))',
  				foreground: 'hsl(var(--sidebar-foreground))',
  				primary: 'hsl(var(--sidebar-primary))',
  				'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
  				accent: 'hsl(var(--sidebar-accent))',
  				'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
  				border: 'hsl(var(--sidebar-border))',
  				ring: 'hsl(var(--sidebar-ring))'
  			}
  		},
  		borderRadius: {
  			lg: 'var(--radius)',
  			md: 'calc(var(--radius) - 2px)',
  			sm: 'calc(var(--radius) - 4px)'
  		},
  		keyframes: {
  			'accordion-down': {
  				from: {
  					height: '0'
  				},
  				to: {
  					height: 'var(--radix-accordion-content-height)'
  				}
  			},
  			'accordion-up': {
  				from: {
  					height: 'var(--radix-accordion-content-height)'
  				},
  				to: {
  					height: '0'
  				}
  			}
  		},
  		animation: {
  			'accordion-down': 'accordion-down 0.2s ease-out',
  			'accordion-up': 'accordion-up 0.2s ease-out'
  		}
  	}
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
